name: Prepare Node.js Environment
description: Prepares the environment with Node.js and dependencies

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14  # Choose the Node.js version you need
    - name: Install dependencies
      shell: bash
      run: npm install  # Install project dependencies

    