name: Continuous Integration
run-name: ${{ github.workflow }} run for ${{ github.actor }} in ${{ github.ref_name }}

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "15 2 * * *"

defaults:
  run:
    shell: bash
    working-directory: ./

concurrency:
  group: ${{ github.workflow }}-${{ github.actor }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  ENVIRONMENT_TYPE: continuous_integration
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  eslint:
    name: Eslint Static Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install # Install project dependencies
      - uses: bradennapier/eslint-plus-action@v3.4.2

  prettier:
    name: Prettier JavaScript Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --check ./**/*.{js,html}

  presubmit:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Locally
        uses: actions/checkout@v3
      - name: Prepare Environment
        uses: ./.github/actions/prepare
      - name: Test Js
        uses: ./.github/actions/test
