name: Continuous Integration
run-name: ${{ github.workflow }} run for ${{ github.actor }} in ${{ github.ref_name }}

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "15 2 * * *"

defaults:
  run:
    shell: bash
    working-directory: ./

concurrency:
  group: ${{ github.workflow }}-${{ github.actor }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  ENVIRONMENT_TYPE: continuous_integration

jobs:

  eslint:
    name: Eslint Static Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsx

  prettier:
    name: Prettier JavaScript Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js}

  presubmit:
    name: Continuous Integration
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code Locally
        uses: actions/checkout@v3
      - name: Prepare Environment
        uses: ./.github/actions/prepare
      - name: Test Js
        uses: ./.github/actions/test
  

  

